services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: dutch-groceries
      POSTGRES_USER: dutch-groceries
      POSTGRES_PASSWORD: dutch-groceries
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: lucas-sandery
    ports:
      - '8080:8080'

  redis:
    image: bitnami/redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - '6379:6379'

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
