services:
  caddy:
    image: caddy:2
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dutch_groceries_network

networks:
  dutch_groceries_network:
    name: dutch-groceries-network
    external: true

volumes:
  caddy_data:
  caddy_config:
