services:
  blue-app:
    image: ghcr.io/bacali95/dutch-groceries-app:${APP_VERSION}
    restart: always
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: curl -f http://localhost:3000/status
      interval: 10s
      timeout: 5s
      retries: 5

  green-app:
    image: ghcr.io/bacali95/dutch-groceries-app:${APP_VERSION}
    restart: always
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: curl -f http://localhost:3000/status
      interval: 10s
      timeout: 5s
      retries: 5
