name: Deploy Caddy

on:
  push:
    branches:
      - main
    paths:
      - 'caddy/**'
      - '.github/workflows/deploy-caddy.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Cloudflare CLI
        run: |
          curl --location --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb 
          sudo dpkg -i cloudflared.deb

      - name: Alter SSH config
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" >> ~/.ssh/id_ed25519
          echo "Host dutch-groceries-server
            ProxyCommand cloudflared access ssh --hostname %h
            HostName ${{ secrets.SERVER_HOSTNAME }}
            User ${{ secrets.SERVER_USERNAME }}
          " > ~/.ssh/config
          chmod 400 ~/.ssh/id_ed25519

      - name: Deploy Caddy
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r caddy dutch-groceries-server:~/

          ssh dutch-groceries-server -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t << EOF
            cd caddy
            docker compose down
            docker compose up -d
          EOF
